// flow-typed signature: bdef8593bf1422557ee8374846b64a6c
// flow-typed version: <<STUB>>/flow-bin-ci_v^0.1.1/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-bin-ci'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-bin-ci' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-bin-ci/lib/cli' {
  declare module.exports: any;
}

declare module 'flow-bin-ci/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-bin-ci/lib/cli.js' {
  declare module.exports: $Exports<'flow-bin-ci/lib/cli'>;
}
declare module 'flow-bin-ci/lib/index.js' {
  declare module.exports: $Exports<'flow-bin-ci/lib/index'>;
}
